### PR TITLE
Added note about timing attacks

### PR DESCRIPTION
**Pull request by perpetual-hydrofoil**

### CODE REVIEW

**Comment by savsgio** [comment]
Hi @jamiesonbecker,

The official fasthttp organization is maintaining this repo in https://github.com/fasthttp/router.
It has some improvements and optimizations in performance.

Thanks.

**Comment by savsgio** [comment]
I will have the pleasure to accept a PR. 😄

**Comment by perpetual-hydrofoil** [comment]
Ok, I submitted the PR to the fasthttp org, thank you! Submitting another PR here to update this README, since Google believes this is the canonical repo. :)

**Comment by perpetual-hydrofoil** [comment]
Incidentally, are there two active repos? It seems like you are both maintaining this?

**Pull request closed without merging**
