### PR TITLE
Replace Params with ctx.UserValues 

### PR DESCRIPTION
**Pull request by yunspace**
This PR uses: `handle(ctx *fasthttp.RequestCtx)`
Instead of: `handle(ctx *fasthttp.RequestCtx, ps fasthttprouter.Params)`

And

Replaces Params with `RequestCtx.UserValues`

So that:

1. Chaining of other fasthttp based middleware functions is much easier.
2. Removes the only major memory allocation that is happening in `fasthttprouter` and `httprouter`

This will break the current API for existing users though...

### CODE REVIEW

**Comment by yunspace** [comment]
If anyone is interested, I've made a fork of this change at: https://github.com/gofury/furyroad 

It's still very much work in progress, but so far so good using it for work projects.

**Comment by buaazp** [comment]
Interesting. Use `fasthttprouter.Params` for handler is JUST because I forked from `fasthttp` in begining. I think compatibility with fasthttp midwares is more important following the original `fasthttp` repo.

I will merge this PR in a few days.

**Comment by yunspace** [comment]
Awesome thanks. I'll remove my fork once merged.

The original `httprouter.Param` also had the same compatibility issues with standard `net/http` middleware and chaining libraries such as https://github.com/justinas/alice. This is where `fatshttp` library sets itself apart nicely by offering helpful features such `ctx.UserValues`.

**Comment by buaazp** [comment]
I want to rebase the origin `httprouter`'s latest commits for the first release. To fix the merge conflicts I will force push a new commit to the master branch.
Can you merge your all 3 commits in this PR to one commit? Because I had to fix the boring conflicts. 
Or if you have time, you can try to fix them.

**Comment by buaazp** [comment]
Or you can reopen a new PR for this target base on my new master branch.

**Comment by buaazp** [comment]
Woooo. Finally I succ merged your commits into master branch now.

Thanks for your work again~

**Comment by yunspace** [comment]
Sorry haven't been check email often these days, surprised that the rebase resulted in 80+ commits. Thanks for merging.

**Comment by buaazp** [comment]
✌️

**Pull request closed without merging**
