### PR TITLE
Updated README to show new repo location

### PR DESCRIPTION
**Pull request by perpetual-hydrofoil**
Congrats on being chosen as the official router for fasthttp! Also suggest (read only) archiving this repository.

### CODE REVIEW

**Comment by phuslu** [comment]
Bad PR with *FUD*

**Comment by savsgio** [comment]
This repository, it's not already the main repository, so this PR it's not already valid.

The [fasthttp/router](https://github.com/fasthttp/router) it's standalone and not depends from other repository.
We are rewrote the full code and based on directly of [julienschmidt/httprouter](https://github.com/julienschmidt/httprouter).

So please, @jamiesonbecker, close this PR!

**Comment by perpetual-hydrofoil** [comment]
@savsgio ok, you are a committer on that repo. Clearly this repo is abandoned and hasn't had any commits (or even response to this pull req) for ~ 1 year. Doing as you request.

**Comment by perpetual-hydrofoil** [comment]
@savsgio Please also see and comment on https://github.com/buaazp/fasthttprouter/issues/55 if the situation has changed in the nearly 12 months since that issue was opened. Thanks.

**Comment by savsgio** [comment]
> @savsgio ok, you are a committer on that repo. Clearly this repo is abandoned and hasn't had any commits (or even response to this pull req) for ~ 1 year. Doing as you request.

Thanks!

**Pull request closed without merging**
